"""
Phase 1 tests: validate WakeWordStreamHandler detects "hey robot" from real
audio and does not false-trigger on silence or unrelated speech.

Samples are generated by macOS `say` + `afconvert` at 16 kHz / mono / 16-bit.
Run:  pytest tests/hardware/test_wake_word.py -v
"""

import os
import wave

from src.hardware.wake_word import WakeWordStreamHandler

SAMPLES = os.path.join(os.path.dirname(__file__), "samples")
CHUNK_BYTES = 2730  # matches browser output: 1365 int16 samples @ 16 kHz


def _feed_wav(handler: WakeWordStreamHandler, filename: str) -> bool:
    """Feed a WAV file to the handler in browser-sized chunks. Returns True if detected."""
    path = os.path.join(SAMPLES, filename)
    with wave.open(path, "rb") as wf:
        assert wf.getframerate() == 16000, "sample must be 16 kHz"
        assert wf.getnchannels() == 1, "sample must be mono"
        assert wf.getsampwidth() == 2, "sample must be 16-bit"
        chunk_frames = CHUNK_BYTES // 2
        while True:
            data = wf.readframes(chunk_frames)
            if not data:
                break
            if handler.process_chunk(data):
                return True
    return False


def _silence(seconds: float) -> bytes:
    """Generate zero-amplitude PCM for the given duration at 16 kHz mono 16-bit."""
    return b"\x00\x00" * int(16000 * seconds)


def _feed_pcm(handler: WakeWordStreamHandler, pcm: bytes) -> bool:
    """Feed raw PCM bytes to the handler in browser-sized chunks."""
    for offset in range(0, len(pcm), CHUNK_BYTES):
        if handler.process_chunk(pcm[offset : offset + CHUNK_BYTES]):
            return True
    return False


# ── Detection tests ────────────────────────────────────────────────────────────

def test_detects_hey_robot():
    assert _feed_wav(WakeWordStreamHandler(), "hey_robot.wav"), (
        "WakeWordStreamHandler did not detect 'hey robot' in the sample"
    )


def test_no_false_positive_on_silence():
    assert not _feed_pcm(WakeWordStreamHandler(), _silence(3)), (
        "WakeWordStreamHandler falsely triggered on 3 seconds of silence"
    )


def test_no_false_positive_on_unrelated_speech():
    handler = WakeWordStreamHandler()
    for filename in ("hello_world.wav", "what_time_is_it.wav"):
        handler.reset()
        assert not _feed_wav(handler, filename), (
            f"WakeWordStreamHandler falsely triggered on '{filename}'"
        )


def test_reset_clears_state():
    """After a detection, reset() should allow a second detection."""
    handler = WakeWordStreamHandler()
    assert _feed_wav(handler, "hey_robot.wav")
    handler.reset()
    assert _feed_wav(handler, "hey_robot.wav")


def test_silence_before_hey_robot():
    """Wake word preceded by 2 seconds of silence should still be detected."""
    handler = WakeWordStreamHandler()
    _feed_pcm(handler, _silence(2))  # prime with silence, ignore result
    assert _feed_wav(handler, "hey_robot.wav"), (
        "Failed to detect wake word after leading silence"
    )
